language: ruby
cache: bundler

rvm:
  - 2.0.0

script: 'bundle exec rake'

notifications:
  email:
    recipients:
      - aleksander.wdowinski@netguru.co
    on_failure: change
    on_success: never
